server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useSSL=false
    username: root
    password: pass@123
  h2:
    console:
      enabled: true
  jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect